"use client";
import { useActionState, useState } from "react";
import { useFormStatus } from "react-dom";
import { saveWebsiteDraftAction, type ActionState } from "../actions";
import type { AboutContent } from "@/lib/data/websiteContentTypes";
const input="mt-1.5 w-full rounded-lg border border-border bg-secondary px-3.5 py-2.5 text-sm text-navy-deep outline-none focus:border-cyan focus:bg-card";
function Field({label,value,onChange,textarea=false,rows=3}:{label:string;value?:string;onChange:(v:string)=>void;textarea?:boolean;rows?:number}){return <label className="block text-sm font-medium text-navy-deep">{label}{textarea?<textarea rows={rows} value={value||""} onChange={e=>onChange(e.target.value)} className={input+" resize-y"}/>:<input value={value||""} onChange={e=>onChange(e.target.value)} className={input}/>}</label>}
function Section({n,title,children}:{n:number;title:string;children:React.ReactNode}){return <section className="surface-card p-6"><div className="flex items-center gap-3"><span className="grid h-7 w-7 place-items-center rounded-full bg-accent text-xs font-bold text-navy">{n}</span><h2 className="text-sm font-semibold text-navy-deep">{title}</h2></div><div className="mt-5 space-y-4">{children}</div></section>}
function Save(){const {pending}=useFormStatus();return <button disabled={pending} className="rounded-full bg-navy px-6 py-3 text-sm font-semibold text-primary-foreground disabled:opacity-60">{pending?"Saving…":"Save draft"}</button>}
export function AboutEditorForm({content}:{content:AboutContent}){const [state,action]=useActionState(saveWebsiteDraftAction,{} as ActionState);const [form,setForm]=useState<AboutContent>(content);const set=(k:keyof AboutContent,v:string)=>setForm(f=>({...f,[k]:v}));return <form action={action} className="space-y-5"><input type="hidden" name="pageKey" value="about"/><input type="hidden" name="content" value={JSON.stringify(form)}/><Section n={1} title="Page header"><Field label="Page title" value={form.pageTitle} onChange={v=>set("pageTitle",v)}/><Field label="Introduction" value={form.introduction} onChange={v=>set("introduction",v)} textarea rows={3}/></Section><Section n={2} title="Our approach"><Field label="Eyebrow" value={form.approachEyebrow} onChange={v=>set("approachEyebrow",v)}/><Field label="Heading" value={form.approachHeading} onChange={v=>set("approachHeading",v)} textarea rows={2}/><Field label="Who we are" value={form.whoWeAre} onChange={v=>set("whoWeAre",v)} textarea rows={8}/></Section><Section n={3} title="About imagery"><Field label="Primary image path / URL" value={form.aboutImagePath} onChange={v=>set("aboutImagePath",v)}/><Field label="Primary image alt text" value={form.aboutImageAlt} onChange={v=>set("aboutImageAlt",v)}/><Field label="Secondary image path / URL" value={form.aboutSecondaryImagePath} onChange={v=>set("aboutSecondaryImagePath",v)}/><Field label="Secondary image alt text" value={form.aboutSecondaryImageAlt} onChange={v=>set("aboutSecondaryImageAlt",v)}/></Section><Section n={4} title="Mission, vision & values"><Field label="Mission" value={form.mission} onChange={v=>set("mission",v)} textarea rows={3}/><Field label="Vision" value={form.vision} onChange={v=>set("vision",v)} textarea rows={3}/><Field label="Values" value={form.values} onChange={v=>set("values",v)} textarea rows={3}/></Section><Section n={5} title="Quality & professional standards"><Field label="Quality section heading" value={form.qualityHeading} onChange={v=>set("qualityHeading",v)}/><Field label="Quality statement" value={form.qualityStatement} onChange={v=>set("qualityStatement",v)} textarea rows={5}/><Field label="Standards section heading" value={form.professionalStandardsHeading} onChange={v=>set("professionalStandardsHeading",v)}/><Field label="Professional standards / licensing / accreditation" value={form.professionalStandards} onChange={v=>set("professionalStandards",v)} textarea rows={5}/></Section><Section n={6} title="Call to action"><div className="grid gap-4 sm:grid-cols-2"><Field label="CTA label" value={form.ctaLabel} onChange={v=>set("ctaLabel",v)}/><Field label="CTA destination" value={form.ctaHref} onChange={v=>set("ctaHref",v)}/></div></Section>{state.error?<p className="text-sm text-destructive">{state.error}</p>:null}<Save/></form>}
