import Link from "next/link";
import Image from "next/image";
import { Target, Eye, HeartHandshake, ClipboardCheck, ShieldCheck, Check, Sparkles } from "lucide-react";
import { PageHeader } from "./SiteLayout";
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion";
import { WhatsAppIcon } from "./WhatsAppButton";
import { siteConfig } from "@/data/siteContent";
import type { AboutContent, FaqContent, PackagesContent } from "@/lib/data/websiteContentTypes";
import { defaultAboutContent, defaultFaqContent, defaultPackagesContent } from "@/lib/data/websitePageDefaults";

export function AboutPageContent({ content }: { content: AboutContent }) {
  const c = { ...defaultAboutContent, ...content };
  const pillars = [{ icon: Target, title: "Mission", body: c.mission }, { icon: Eye, title: "Vision", body: c.vision }, { icon: HeartHandshake, title: "Values", body: c.values }];
  return <>
    <PageHeader eyebrow="About Salem" title={c.pageTitle} lead={c.introduction} />
    <section className="bg-background py-16 lg:py-24"><div className="mx-auto grid max-w-7xl gap-12 px-5 sm:px-6 lg:grid-cols-[1fr_1fr] lg:items-center"><div className="min-w-0"><span className="text-xs font-semibold uppercase tracking-[0.22em] text-purple">{c.approachEyebrow}</span><h2 className="mt-4 text-3xl font-semibold tracking-tight text-navy-deep sm:text-4xl">{c.approachHeading}</h2><div className="mt-6 whitespace-pre-line text-base leading-relaxed text-muted-foreground">{c.whoWeAre}</div><Link href={c.ctaHref} className="mt-8 inline-flex rounded-full bg-navy px-6 py-3.5 text-sm font-semibold text-primary-foreground shadow-soft transition-transform hover:scale-[1.03]">{c.ctaLabel}</Link></div><div className="grid min-w-0 gap-4 sm:grid-cols-2"><Image src={c.aboutImagePath} alt={c.aboutImageAlt} loading="lazy" width={900} height={700} className="h-72 w-full rounded-3xl object-cover shadow-soft sm:h-full" /><Image src={c.aboutSecondaryImagePath} alt={c.aboutSecondaryImageAlt} loading="lazy" width={900} height={700} className="h-72 w-full rounded-3xl object-cover shadow-soft sm:mt-8 sm:h-full" /></div></div></section>
    <section className="bg-secondary py-16 lg:py-24"><div className="mx-auto max-w-7xl px-5 sm:px-6"><div className="grid gap-5 md:grid-cols-3">{pillars.map(({ icon: Icon, title, body }) => <div key={title} className="surface-card p-7"><span className="grid h-11 w-11 place-items-center rounded-xl bg-accent text-navy"><Icon className="h-5 w-5" /></span><h3 className="mt-5 text-lg font-semibold text-navy-deep">{title}</h3><p className="mt-2 whitespace-pre-line text-sm leading-relaxed text-muted-foreground">{body}</p></div>)}</div></div></section>
    <section className="bg-background py-16 lg:py-24"><div className="mx-auto grid max-w-7xl gap-10 px-5 sm:px-6 lg:grid-cols-2"><div className="surface-card p-7 sm:p-9"><span className="grid h-11 w-11 place-items-center rounded-xl bg-accent text-navy"><ShieldCheck className="h-5 w-5" /></span><h2 className="mt-5 text-2xl font-semibold text-navy-deep">{c.qualityHeading}</h2><p className="mt-4 whitespace-pre-line text-sm leading-relaxed text-muted-foreground">{c.qualityStatement}</p></div><div className="surface-card p-7 sm:p-9"><span className="grid h-11 w-11 place-items-center rounded-xl bg-accent text-navy"><ClipboardCheck className="h-5 w-5" /></span><h2 className="mt-5 text-2xl font-semibold text-navy-deep">{c.professionalStandardsHeading}</h2><p className="mt-4 whitespace-pre-line text-sm leading-relaxed text-muted-foreground">{c.professionalStandards}</p></div></div></section>
  </>;
}

export function FaqPageContent({ content }: { content: FaqContent }) {
  const c = { ...defaultFaqContent, ...content, groups: content.groups?.length ? content.groups : defaultFaqContent.groups };
  return <><PageHeader eyebrow="Frequently Asked Questions" title={c.pageTitle!} lead={c.introduction!}/><section className="bg-background py-14 lg:py-20"><div className="mx-auto max-w-4xl px-5 sm:px-6">{c.groups!.map(g => <div key={g.id} className="mb-10 last:mb-0"><h2 className="text-sm font-semibold uppercase tracking-[0.2em] text-purple">{g.heading}</h2><Accordion type="single" collapsible className="mt-4 rounded-2xl border border-border bg-card px-2 shadow-soft">{g.items.map((item,i) => <AccordionItem key={item.id} value={`${g.id}-${i}`} className="border-border px-4"><AccordionTrigger className="text-sm font-semibold text-navy-deep hover:no-underline">{item.question}</AccordionTrigger><AccordionContent className="whitespace-pre-line text-sm leading-relaxed text-muted-foreground">{item.answer}</AccordionContent></AccordionItem>)}</Accordion></div>)}<div className="mt-12 flex flex-col items-start gap-4 rounded-2xl border border-border bg-secondary p-6 sm:flex-row sm:items-center sm:justify-between"><div><h3 className="text-base font-semibold text-navy-deep">{c.ctaHeading}</h3><p className="mt-1 text-sm text-muted-foreground">{c.ctaDescription}</p></div><div className="flex flex-wrap gap-3"><a href={siteConfig.phone.whatsappHref} target="_blank" rel="noopener noreferrer" className="inline-flex items-center gap-2 rounded-full bg-whatsapp px-5 py-2.5 text-sm font-semibold text-white shadow-soft"><WhatsAppIcon className="h-4 w-4"/> WhatsApp us</a><Link href="/contact" className="inline-flex items-center gap-2 rounded-full border border-border px-5 py-2.5 text-sm font-semibold text-navy">Contact page</Link></div></div></div></section></>;
}

export function PackagesPageContent({ content }: { content: PackagesContent }) {
  const c = { ...defaultPackagesContent, ...content, packages: content.packages?.length ? content.packages : defaultPackagesContent.packages };
  return <><PageHeader eyebrow="Health Packages" title={c.pageTitle!} lead={c.introduction!}/><section className="bg-background py-14 lg:py-20"><div className="mx-auto max-w-7xl px-5 sm:px-6"><div className="grid gap-6 md:grid-cols-2 lg:grid-cols-3">{c.packages!.map(p => <article key={p.id} className={`surface-card flex flex-col p-7 ${p.featured ? "border-cyan/50 shadow-glow" : ""}`}>{p.featured ? <span className="mb-4 inline-flex w-fit items-center gap-1.5 rounded-full bg-navy px-3 py-1 text-[0.7rem] font-semibold uppercase tracking-[0.12em] text-primary-foreground"><Sparkles className="h-3.5 w-3.5"/> Most comprehensive</span> : null}<h2 className="text-xl font-semibold text-navy-deep">{p.name}</h2><p className="mt-2 text-sm leading-relaxed text-muted-foreground">{p.description}</p><ul className="mt-6 space-y-3 border-t border-border pt-6">{p.tests.map(t => <li key={t} className="flex items-start gap-3 text-sm text-navy"><Check className="mt-0.5 h-4 w-4 shrink-0 text-cyan"/><span>{t}</span></li>)}</ul><p className="mt-6 text-xs text-muted-foreground">{c.pricingNote}</p><Link href="/book" className={`mt-4 inline-flex items-center justify-center rounded-full px-5 py-3 text-sm font-semibold ${p.featured ? "bg-navy text-primary-foreground" : "border border-border text-navy"}`}>{p.ctaLabel || "Enquire about this package"}</Link></article>)}</div></div></section></>;
}
