import Link from "next/link";
import Image from "next/image";
import { Target, Eye, HeartHandshake, ClipboardCheck, ShieldCheck, Check, Sparkles } from "lucide-react";
import { PageHeader } from "@/components/salem/SiteLayout";
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion";
import { WhatsAppIcon } from "@/components/salem/WhatsAppButton";
import { siteConfig } from "@/data/siteContent";
import { canonical } from "@/lib/seo";
import type { AboutContent, FaqContent, PackagesContent, BookingContent, ResultsContent } from "@/lib/data/websiteContentTypes";

export const defaultAboutContent: Required<Pick<AboutContent,"pageTitle"|"introduction"|"approachEyebrow"|"approachHeading"|"whoWeAre"|"aboutImagePath"|"aboutImageAlt"|"aboutSecondaryImagePath"|"aboutSecondaryImageAlt"|"mission"|"vision"|"values"|"qualityStatement"|"professionalStandards"|"qualityHeading"|"professionalStandardsHeading"|"ctaLabel"|"ctaHref">> = {
  pageTitle:"A laboratory built by scientists who take results personally.", introduction:"Salem Medical Laboratories exists to close the gap between fast diagnostics and trustworthy diagnostics.", approachEyebrow:"Our approach", approachHeading:"Founded on one question: can this result be trusted?", whoWeAre:"Every sample that enters our laboratory is tracked from collection to release. No report leaves the building without a laboratory scientist's review.\n\nWe run automated haematology, chemistry, immunoassay and molecular platforms, supported by a home collection service for patients who prefer to be tested at home.", aboutImagePath:"/images/hero-lab.jpg", aboutImageAlt:"Scientists working in the Salem Medical Laboratories analysis bay", aboutSecondaryImagePath:"/images/svc-micro.jpg", aboutSecondaryImageAlt:"Microbiology plate review under a microscope at Salem", mission:"To make accurate diagnostics accessible, explained in language every patient understands.", vision:"To be a trusted independent laboratory known for precision and patient dignity.", values:"Integrity in every result, empathy at every desk, and discipline in every process.", qualityStatement:"Internal controls run before patient samples are processed, analysers are kept on a calibration schedule, and every released report carries the reviewing scientist's name.", professionalStandards:"Licensing and accreditation details will be listed here once confirmed and supplied by the laboratory.", qualityHeading:"Quality assurance", professionalStandardsHeading:"Certifications & accreditation", ctaLabel:"Visit our facility", ctaHref:"/contact"
};

export function AboutPageContent({ content }: { content: AboutContent }) {
  const c = { ...defaultAboutContent, ...content };
  const pillars = [{ icon: Target, title:"Mission", body:c.mission }, { icon: Eye, title:"Vision", body:c.vision }, { icon: HeartHandshake, title:"Values", body:c.values }];
  return <>
    <PageHeader eyebrow="About Salem" title={c.pageTitle} lead={c.introduction} />
    <section className="bg-background py-16 lg:py-24"><div className="mx-auto grid max-w-7xl gap-12 px-5 sm:px-6 lg:grid-cols-[1fr_1fr] lg:items-center"><div className="min-w-0"><span className="text-xs font-semibold uppercase tracking-[0.22em] text-purple">{c.approachEyebrow}</span><h2 className="mt-4 text-3xl font-semibold tracking-tight text-navy-deep sm:text-4xl">{c.approachHeading}</h2><div className="mt-6 whitespace-pre-line text-base leading-relaxed text-muted-foreground">{c.whoWeAre}</div><Link href={c.ctaHref} className="mt-8 inline-flex rounded-full bg-navy px-6 py-3.5 text-sm font-semibold text-primary-foreground shadow-soft transition-transform hover:scale-[1.03]">{c.ctaLabel}</Link></div><div className="grid min-w-0 gap-4 sm:grid-cols-2"><Image src={c.aboutImagePath} alt={c.aboutImageAlt} loading="lazy" width={900} height={700} className="h-72 w-full rounded-3xl object-cover shadow-soft sm:h-full" /><Image src={c.aboutSecondaryImagePath} alt={c.aboutSecondaryImageAlt} loading="lazy" width={900} height={700} className="h-72 w-full rounded-3xl object-cover shadow-soft sm:mt-8 sm:h-full" /></div></div></section>
    <section className="bg-secondary py-16 lg:py-24"><div className="mx-auto max-w-7xl px-5 sm:px-6"><div className="grid gap-5 md:grid-cols-3">{pillars.map(({icon:Icon,title,body})=><div key={title} className="surface-card p-7"><span className="grid h-11 w-11 place-items-center rounded-xl bg-accent text-navy"><Icon className="h-5 w-5" /></span><h3 className="mt-5 text-lg font-semibold text-navy-deep">{title}</h3><p className="mt-2 whitespace-pre-line text-sm leading-relaxed text-muted-foreground">{body}</p></div>)}</div></div></section>
    <section className="bg-background py-16 lg:py-24"><div className="mx-auto grid max-w-7xl gap-10 px-5 sm:px-6 lg:grid-cols-2"><div className="surface-card p-7 sm:p-9"><span className="grid h-11 w-11 place-items-center rounded-xl bg-accent text-navy"><ShieldCheck className="h-5 w-5" /></span><h2 className="mt-5 text-2xl font-semibold text-navy-deep">{c.qualityHeading}</h2><p className="mt-4 whitespace-pre-line text-sm leading-relaxed text-muted-foreground">{c.qualityStatement}</p></div><div className="surface-card p-7 sm:p-9"><span className="grid h-11 w-11 place-items-center rounded-xl bg-accent text-navy"><ClipboardCheck className="h-5 w-5" /></span><h2 className="mt-5 text-2xl font-semibold text-navy-deep">{c.professionalStandardsHeading}</h2><p className="mt-4 whitespace-pre-line text-sm leading-relaxed text-muted-foreground">{c.professionalStandards}</p></div></div></section>
  </>;
}

export const defaultFaqContent: FaqContent = { pageTitle:"Answers before you even have to ask.", introduction:"Can't find what you're looking for? Reach out and our team will help directly.", groups:[{id:"booking",heading:"Booking & appointments",items:[{id:"book",question:"How do I book a test?",answer:"Use the Book an Appointment page to choose a date, time and location, or call/WhatsApp our front desk and we'll confirm your booking personally."},{id:"walkin",question:"Can I book for a walk-in visit instead of scheduling ahead?",answer:"Yes. Walk-ins are welcome during opening hours, though booking ahead helps us prepare for your specific test."},{id:"request",question:"Do I need a doctor's request form?",answer:"Some tests require a referring doctor's request; others can be booked directly. If you're unsure, share the test name with our front desk and they'll confirm."}]},{id:"prep",heading:"Preparing for your test",items:[{id:"fast",question:"Do I need to fast before my test?",answer:"Some tests, such as fasting blood sugar or a lipid profile, require 8–12 hours of fasting. Your booking confirmation will tell you if fasting applies to your test."},{id:"bring",question:"What should I bring on the day?",answer:"Bring a valid ID, your doctor's request form if you have one, and your booking reference. If it's a repeat test, previous results are helpful but not required."}]},{id:"home",heading:"Home sample collection",items:[{id:"how",question:"How does home sample collection work?",answer:"Book a home visit through our Home Collection page or by WhatsApp. A trained phlebotomist arrives at your chosen time with sterile, single-use equipment to collect your sample."},{id:"coverage",question:"Is home collection available everywhere?",answer:"Coverage depends on your location. Let us know your address when booking and we'll confirm whether home collection is available for you."}]},{id:"results",heading:"Accessing your results",items:[{id:"ready",question:"How will I know when my result is ready?",answer:"We notify you by SMS, email or WhatsApp once your report has been reviewed and released, along with your lab reference number and a one-time access code."},{id:"view",question:"How do I view my result online?",answer:"Visit the Access Your Results page and enter your lab reference number and one-time access code to securely view or download your report."},{id:"help",question:"Can I get help understanding my result?",answer:"Yes. Contact our records desk and a member of our team will arrange a call to walk you through your report. We recommend discussing results with your physician for clinical decisions."}]}], ctaHeading:"Still have a question?", ctaDescription:"Our team replies quickly on WhatsApp or by phone." };

export function FaqPageContent({ content }: { content: FaqContent }) { const c={...defaultFaqContent,...content}; const groups=content.groups?.length ? content.groups : defaultFaqContent.groups; const title=c.pageTitle ?? defaultFaqContent.pageTitle; const introduction=c.introduction ?? defaultFaqContent.introduction; return <><PageHeader eyebrow="Frequently Asked Questions" title={title} lead={introduction}/><section className="bg-background py-14 lg:py-20"><div className="mx-auto max-w-4xl px-5 sm:px-6">{groups.map(g=><div key={g.id} className="mb-10 last:mb-0"><h2 className="text-sm font-semibold uppercase tracking-[0.2em] text-purple">{g.heading}</h2><Accordion type="single" collapsible className="mt-4 rounded-2xl border border-border bg-card px-2 shadow-soft">{g.items.map((item,i)=><AccordionItem key={item.id} value={`${g.id}-${i}`} className="border-border px-4"><AccordionTrigger className="text-sm font-semibold text-navy-deep hover:no-underline">{item.question}</AccordionTrigger><AccordionContent className="whitespace-pre-line text-sm leading-relaxed text-muted-foreground">{item.answer}</AccordionContent></AccordionItem>)}</Accordion></div>)}<div className="mt-12 flex flex-col items-start gap-4 rounded-2xl border border-border bg-secondary p-6 sm:flex-row sm:items-center sm:justify-between"><div><h3 className="text-base font-semibold text-navy-deep">{c.ctaHeading}</h3><p className="mt-1 text-sm text-muted-foreground">{c.ctaDescription}</p></div><div className="flex flex-wrap gap-3"><a href={siteConfig.phone.whatsappHref} target="_blank" rel="noopener noreferrer" className="inline-flex items-center gap-2 rounded-full bg-whatsapp px-5 py-2.5 text-sm font-semibold text-white shadow-soft"><WhatsAppIcon className="h-4 w-4"/> WhatsApp us</a><Link href="/contact" className="inline-flex items-center gap-2 rounded-full border border-border px-5 py-2.5 text-sm font-semibold text-navy">Contact page</Link></div></div></div></section></>; }

export const defaultPackagesContent: PackagesContent = { pageTitle:"Screening packages built around real lives, not long lists.", introduction:"Each package bundles the tests that matter, with a clear written summary you can take to your doctor.", pricingNote:"Pricing confirmed when you enquire or book.", packages:[{id:"basic",name:"Basic Health Screening",description:"A dependable annual baseline for healthy adults.",tests:["Full blood count","Blood sugar (FBS)","Urinalysis","Blood pressure & BMI review"]},{id:"executive",name:"Executive Health Screening",description:"Our most complete profile for leaders and frequent travellers.",featured:true,tests:["Full blood count & ESR","Liver, kidney and lipid panels","HbA1c & thyroid profile","PSA / cervical screening"]},{id:"women",name:"Women's Health",description:"Hormonal, reproductive and wellness markers for women.",tests:["Hormonal profile","Pap smear / cytology","Iron studies","Thyroid function"]},{id:"men",name:"Men's Health",description:"Cardiometabolic and prostate-focused screening for men.",tests:["PSA","Lipid profile","Testosterone","Liver & kidney function"]},{id:"corporate",name:"Corporate Screening",description:"On-site collection and consolidated reporting for teams.",tests:["Pre-employment panel","On-site sample collection","Group HR reporting","Annual review"]},{id:"preventive",name:"Preventive Health Package",description:"Early-detection markers for families with risk history.",tests:["Cancer marker screen","Diabetes risk panel","Cardiac markers","Vitamin D & B12"]}]};
export function PackagesPageContent({ content }: { content: PackagesContent }) { const c={...defaultPackagesContent,...content}; const packages=content.packages?.length ? content.packages : defaultPackagesContent.packages; const title=c.pageTitle ?? defaultPackagesContent.pageTitle; const introduction=c.introduction ?? defaultPackagesContent.introduction; return <><PageHeader eyebrow="Health Packages" title={title} lead={introduction}/><section className="bg-background py-14 lg:py-20"><div className="mx-auto max-w-7xl px-5 sm:px-6"><div className="grid gap-6 md:grid-cols-2 lg:grid-cols-3">{packages.map(p=><article key={p.id} className={`surface-card flex flex-col p-7 ${p.featured?"border-cyan/50 shadow-glow":""}`}>{p.featured?<span className="mb-4 inline-flex w-fit items-center gap-1.5 rounded-full bg-navy px-3 py-1 text-[0.7rem] font-semibold uppercase tracking-[0.12em] text-primary-foreground"><Sparkles className="h-3.5 w-3.5"/> Most comprehensive</span>:null}<h2 className="text-xl font-semibold text-navy-deep">{p.name}</h2><p className="mt-2 text-sm leading-relaxed text-muted-foreground">{p.description}</p><ul className="mt-6 space-y-3 border-t border-border pt-6">{p.tests.map(t=><li key={t} className="flex items-start gap-3 text-sm text-navy"><Check className="mt-0.5 h-4 w-4 shrink-0 text-cyan"/><span>{t}</span></li>)}</ul><p className="mt-6 text-xs text-muted-foreground">{c.pricingNote}</p><Link href="/book" className={`mt-4 inline-flex items-center justify-center rounded-full px-5 py-3 text-sm font-semibold ${p.featured?"bg-navy text-primary-foreground":"border border-border text-navy"}`}>{p.ctaLabel||"Enquire about this package"}</Link></article>)}</div></div></section></>; }

export const defaultBookingContent: BookingContent = { pageTitle:"Booking a test should take two minutes, not two calls.", introduction:"Pick your test, choose a time, and tell us where to meet you. Our front desk confirms every booking personally.", confirmationTitle:"Booking received", confirmationMessage:"Your request has been submitted successfully. Our front desk will contact you to confirm the appointment.", bookingNotice:"Select a test, preferred date and time, then choose whether you will visit the laboratory or request home collection." };
export const defaultResultsContent: ResultsContent = { pageTitle:"Your results. Yours alone.", introduction:"No public patient portal, no shared inbox. Enter your lab reference number and the one-time access code sent to you to view your report.", accessInstructions:"Both fields are printed on your sample receipt and sent by SMS or email when your result is released.", helpMessage:"Didn't receive a code? Contact the laboratory records desk with a valid ID." };
