"use server";
import { revalidatePath } from "next/cache";
import { requireStaff } from "@/lib/auth/session";
import { createStaffAccount, updateStaffProfile, assignStaffRoles, createDepartment, deactivateStaffAccount, reactivateStaffAccount } from "@/lib/data/staff";
import { createStaffSchema, updateStaffSchema, staffStatusSchema } from "@/lib/validation/schemas";
import { STAFF_ROLES, type StaffRole } from "@/lib/auth/permissions";
export interface ActionState { error?: string; ok?: boolean; }
const rolesFromForm=(fd:FormData):StaffRole[]=>Array.from(new Set(fd.getAll("roles").map(String).filter((r):r is StaffRole=>(STAFF_ROLES as string[]).includes(r))));
export async function createStaffAction(_prev:ActionState,fd:FormData):Promise<ActionState>{const staff=await requireStaff();const parsed=createStaffSchema.safeParse({email:fd.get("email"),password:fd.get("password"),fullName:fd.get("fullName"),role:fd.get("role"),qualification:fd.get("qualification")||"",designation:fd.get("designation")||"",phone:fd.get("phone")||""});if(!parsed.success)return{error:parsed.error.issues[0]?.message??"Invalid staff details."};try{await createStaffAccount({email:parsed.data.email,password:parsed.data.password,fullName:parsed.data.fullName,role:parsed.data.role,roles:rolesFromForm(fd),departmentId:String(fd.get("departmentId")||"")||null,qualification:parsed.data.qualification||undefined,designation:parsed.data.designation||undefined,phone:parsed.data.phone||undefined,actorRole:staff.role});}catch(e){return{error:e instanceof Error?e.message:"Could not create staff account."}}revalidatePath("/admin/staff");return{ok:true};}
export async function updateStaffAction(_prev:ActionState,fd:FormData):Promise<ActionState>{const staff=await requireStaff();const parsed=updateStaffSchema.safeParse({staffId:fd.get("staffId"),fullName:fd.get("fullName"),role:fd.get("role"),qualification:fd.get("qualification")||"",designation:fd.get("designation")||"",phone:fd.get("phone")||""});if(!parsed.success)return{error:parsed.error.issues[0]?.message??"Invalid staff details."};try{await updateStaffProfile(parsed.data.staffId,{full_name:parsed.data.fullName,role:parsed.data.role,qualification:parsed.data.qualification||null,designation:parsed.data.designation||null,phone:parsed.data.phone||null,department_id:String(fd.get("departmentId")||"")||null},staff.role);const roles=rolesFromForm(fd);await assignStaffRoles(parsed.data.staffId,roles.length?roles:[parsed.data.role],staff.role,parsed.data.role);}catch(e){return{error:e instanceof Error?e.message:"Could not update staff account."}}revalidatePath("/admin/staff");return{ok:true};}
export async function setStaffStatusAction(_prev:ActionState,fd:FormData):Promise<ActionState>{const staff=await requireStaff();const parsed=staffStatusSchema.safeParse({staffId:fd.get("staffId"),active:fd.get("active")});if(!parsed.success)return{error:"Invalid request."};try{if(parsed.data.active==="true")await reactivateStaffAccount(parsed.data.staffId,staff.role);else await deactivateStaffAccount(parsed.data.staffId,staff.role);}catch(e){return{error:e instanceof Error?e.message:"Could not update staff status."}}revalidatePath("/admin/staff");return{ok:true};}
export async function createDepartmentAction(_prev:ActionState,fd:FormData):Promise<ActionState>{const staff=await requireStaff();const name=String(fd.get("name")||"").trim();if(!name)return{error:"Department name is required."};try{await createDepartment(name,String(fd.get("description")||"").trim()||null,staff.role);}catch(e){return{error:e instanceof Error?e.message:"Could not create department."}}revalidatePath("/admin/staff");return{ok:true};}
