import type { Metadata } from "next";
import Link from "next/link";
import { AdminShell } from "@/components/salem/AdminShell";
import { requireStaff, can } from "@/lib/auth/session";
import { getAdminNavItems } from "@/lib/auth/nav";
import { getAnalyticsSummary } from "@/lib/data/analytics";
import { listAllArticles } from "@/lib/data/seoArticles";
export const dynamic="force-dynamic";
export const metadata: Metadata={title:"SEO Performance | Salem Staff Area",robots:{index:false,follow:false}};
export default async function SeoPerformancePage(){ const staff=await requireStaff(); const nav=getAdminNavItems(staff); if(!can(staff,"analytics.view")) return <AdminShell eyebrow="SEO" title="Not available" staffName={staff.fullName} staffRole={staff.role} navItems={nav}><p className="surface-card p-6">Your role does not have analytics access.</p></AdminShell>; const [summary,articles]=await Promise.all([getAnalyticsSummary(staff.role,30),listAllArticles(staff.role)]); return <AdminShell eyebrow="SEO · Performance" title="SEO performance" lead="Private first-party traffic monitoring for the last 30 days. Search ranking data comes from Google Search Console." staffName={staff.fullName} staffRole={staff.role} navItems={nav}><div className="grid gap-4 sm:grid-cols-3"><div className="surface-card p-5"><p className="text-xs text-muted-foreground">Page views</p><p className="mt-2 text-3xl font-semibold text-navy-deep">{summary.totalViews}</p></div><div className="surface-card p-5"><p className="text-xs text-muted-foreground">Published articles</p><p className="mt-2 text-3xl font-semibold text-navy-deep">{articles.filter(a=>a.status==='published').length}</p></div><div className="surface-card p-5"><p className="text-xs text-muted-foreground">Google Search Console</p><Link className="mt-3 inline-block text-sm font-semibold text-purple" href="https://search.google.com/search-console" target="_blank">Open Search Console →</Link></div></div><div className="mt-6 grid gap-6 lg:grid-cols-2"><div className="surface-card p-6"><h2 className="font-semibold text-navy-deep">Top pages</h2><div className="mt-4 space-y-3">{summary.topPages.map(x=><div key={x.path} className="flex justify-between gap-4 text-sm"><span className="truncate">{x.path}</span><b>{x.views}</b></div>)}</div></div><div className="surface-card p-6"><h2 className="font-semibold text-navy-deep">Traffic sources</h2><div className="mt-4 space-y-3">{summary.sources.map(x=><div key={x.source} className="flex justify-between text-sm"><span>{x.source}</span><b>{x.views}</b></div>)}</div></div></div><div className="mt-6 surface-card p-6"><div className="flex items-center justify-between"><h2 className="font-semibold text-navy-deep">SEO content</h2><Link href="/admin/seo-performance/articles" className="text-sm font-semibold text-purple">Manage articles →</Link></div><p className="mt-2 text-sm text-muted-foreground">Publish useful, original health and laboratory information. Do not publish AI-generated medical claims without clinical review.</p></div></AdminShell>; }
