"use client";
import { useActionState, useMemo, useState } from "react";
import Link from "next/link";
import { Plus, Trash2 } from "lucide-react";
import { useFormStatus } from "react-dom";
import { updateResultTemplateAction, type TemplateActionState } from "../actions";
import type { AdminTemplateWithUsage } from "@/lib/data/testCatalog";
const input = "mt-1.5 w-full rounded-lg border border-border bg-secondary px-3.5 py-2.5 text-sm text-navy-deep outline-none focus:border-cyan focus:bg-card";
type Field = { label: string; inputType: "numeric"|"text"|"select"|"positive_negative"; unit: string; options: string };
const cleanOptions = (v: string) => v.split(",").map(x => x.trim()).filter(Boolean);
function SaveButton(){const {pending}=useFormStatus();return <button disabled={pending} className="rounded-full bg-navy px-6 py-3 text-sm font-semibold text-primary-foreground disabled:opacity-60">{pending?"Saving…":"Save template"}</button>}
export function TemplateEditForm({template}:{template:AdminTemplateWithUsage}){
 const [state,action]=useActionState(updateResultTemplateAction,{} as TemplateActionState);
 const [type,setType]=useState<"field_based"|"table_based">(template.structure_type);
 const [name,setName]=useState(template.name); const [description,setDescription]=useState(template.description??"");
 const [fields,setFields]=useState<Field[]>(template.fields.map(f=>({label:f.label,inputType:f.input_type,unit:f.unit??"",options:Array.isArray(f.options)?f.options.join(", "):""}))); 
 const [columns,setColumns]=useState(template.tableColumns.map(c=>c.column_label)); const [rows,setRows]=useState(template.tableRows.map(r=>r.row_label));
 const fieldsJson=useMemo(()=>JSON.stringify(fields.filter(f=>f.label.trim()).map(f=>({label:f.label.trim(),inputType:f.inputType,unit:f.unit.trim(),options:f.inputType==="select"?cleanOptions(f.options):[]}))),[fields]);
 const columnsJson=JSON.stringify(columns.map(x=>x.trim()).filter(Boolean)); const rowsJson=JSON.stringify(rows.map(x=>x.trim()).filter(Boolean));
 return <form action={action} className="space-y-5"><input type="hidden" name="templateId" value={template.id}/><input type="hidden" name="name" value={name}/><input type="hidden" name="description" value={description}/><input type="hidden" name="structureType" value={type}/><input type="hidden" name="fieldsJson" value={fieldsJson}/><input type="hidden" name="columnsJson" value={columnsJson}/><input type="hidden" name="rowsJson" value={rowsJson}/>
 <section className="surface-card p-6"><h2 className="text-sm font-semibold text-navy-deep">Template details</h2><label className="mt-4 block text-sm font-medium text-navy-deep">Template name<input value={name} onChange={e=>setName(e.target.value)} className={input}/></label><label className="mt-4 block text-sm font-medium text-navy-deep">Internal description<textarea value={description} onChange={e=>setDescription(e.target.value)} rows={3} className={input} placeholder="When should staff use this template?"/></label></section>
 <section className="surface-card p-6"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-sm font-semibold text-navy-deep">Result structure</h2><p className="mt-1 text-xs text-muted-foreground">Keep the structure aligned with the investigation's actual reporting format.</p></div><div className="flex rounded-lg border border-border bg-secondary p-1"><button type="button" onClick={()=>setType("field_based")} className={`rounded-md px-3 py-2 text-xs font-semibold ${type==="field_based"?"bg-card text-navy shadow-soft":"text-muted-foreground"}`}>Parameters</button><button type="button" onClick={()=>setType("table_based")} className={`rounded-md px-3 py-2 text-xs font-semibold ${type==="table_based"?"bg-card text-navy shadow-soft":"text-muted-foreground"}`}>Table</button></div></div>
 {type==="field_based"?<div className="mt-5 space-y-3">{fields.map((f,i)=><div key={i} className="grid gap-2 rounded-xl border border-border bg-secondary/40 p-3 sm:grid-cols-[1fr_150px_120px_1fr_auto] sm:items-end"><label className="text-xs font-semibold text-navy-deep">Parameter<input value={f.label} onChange={e=>setFields(p=>p.map((x,j)=>j===i?{...x,label:e.target.value}:x))} className={input}/></label><label className="text-xs font-semibold text-navy-deep">Input type<select value={f.inputType} onChange={e=>setFields(p=>p.map((x,j)=>j===i?{...x,inputType:e.target.value as Field["inputType"]}:x))} className={input}><option value="text">Text</option><option value="numeric">Numeric</option><option value="positive_negative">Positive / Negative</option><option value="select">Select</option></select></label><label className="text-xs font-semibold text-navy-deep">Unit<input value={f.unit} onChange={e=>setFields(p=>p.map((x,j)=>j===i?{...x,unit:e.target.value}:x))} className={input}/></label><label className="text-xs font-semibold text-navy-deep">Select options<input disabled={f.inputType!=="select"} value={f.options} onChange={e=>setFields(p=>p.map((x,j)=>j===i?{...x,options:e.target.value}:x))} className={input} placeholder="Positive, Negative"/></label><button type="button" disabled={fields.length===1} onClick={()=>setFields(p=>p.filter((_,j)=>j!==i))} className="mb-2 text-destructive disabled:opacity-30"><Trash2 className="h-4 w-4"/></button></div>)}<button type="button" onClick={()=>setFields(p=>[...p,{label:"",inputType:"text",unit:"",options:""}])} className="inline-flex items-center gap-1.5 text-xs font-semibold text-navy"><Plus className="h-3.5 w-3.5"/> Add parameter</button></div>:<div className="mt-5 grid gap-6 sm:grid-cols-2"><div>{columns.map((c,i)=><div key={i} className="mt-2 flex gap-2"><input value={c} onChange={e=>setColumns(p=>p.map((x,j)=>j===i?e.target.value:x))} className={input} placeholder="Column"/><button type="button" disabled={columns.length===1} onClick={()=>setColumns(p=>p.filter((_,j)=>j!==i))} className="mt-2 text-destructive disabled:opacity-30"><Trash2 className="h-4 w-4"/></button></div>)}<button type="button" onClick={()=>setColumns(p=>[...p,""])} className="mt-3 text-xs font-semibold text-navy"><Plus className="h-3.5 w-3.5 inline"/> Add column</button></div><div>{rows.map((r,i)=><div key={i} className="mt-2 flex gap-2"><input value={r} onChange={e=>setRows(p=>p.map((x,j)=>j===i?e.target.value:x))} className={input} placeholder="Row"/><button type="button" disabled={rows.length===1} onClick={()=>setRows(p=>p.filter((_,j)=>j!==i))} className="mt-2 text-destructive disabled:opacity-30"><Trash2 className="h-4 w-4"/></button></div>)}<button type="button" onClick={()=>setRows(p=>[...p,""])} className="mt-3 text-xs font-semibold text-navy"><Plus className="h-3.5 w-3.5 inline"/> Add row</button></div></div>}
 </section>{state.error?<p className="surface-card p-4 text-sm text-destructive">{state.error}</p>:null}{state.ok?<p className="surface-card p-4 text-sm text-emerald-700">Template saved successfully.</p>:null}<div className="flex gap-3"><SaveButton/><Link href="/admin/services/templates" className="rounded-full border border-border px-6 py-3 text-sm font-semibold text-navy">Back</Link></div></form>
}
