update public.website_pages
set draft_content = jsonb_build_object(
  'pageTitle','A laboratory built by scientists who take results personally.',
  'introduction','Salem Medical Laboratories exists to close the gap between fast diagnostics and trustworthy diagnostics.',
  'approachEyebrow','Our approach',
  'approachHeading','Founded on one question: can this result be trusted?',
  'whoWeAre','Every sample that enters our laboratory is tracked from collection to release. No report leaves the building without a laboratory scientist''s review.\n\nWe run automated haematology, chemistry, immunoassay and molecular platforms, supported by a home collection service for patients who prefer to be tested at home.',
  'mission','To make accurate diagnostics accessible, explained in language every patient understands.',
  'vision','To be a trusted independent laboratory known for precision and patient dignity.',
  'values','Integrity in every result, empathy at every desk, and discipline in every process.',
  'qualityHeading','Quality assurance',
  'qualityStatement','Internal controls run before patient samples are processed, analysers are kept on a calibration schedule, and every released report carries the reviewing scientist''s name.',
  'professionalStandardsHeading','Certifications & accreditation',
  'professionalStandards','Salem Medical Laboratories is licensed to operate as a medical diagnostic laboratory. Applicable professional standards and accreditation information can be maintained here by the laboratory administrator.',
  'aboutImagePath','/images/hero-lab.jpg',
  'aboutImageAlt','Scientists working in the Salem Medical Laboratories analysis bay',
  'aboutSecondaryImagePath','/images/svc-micro.jpg',
  'aboutSecondaryImageAlt','Microbiology plate review under a microscope at Salem',
  'ctaLabel','Visit our facility', 'ctaHref','/contact'
)
where page_key='about' and draft_content='{}'::jsonb;

update public.website_pages
set draft_content = '{"pageTitle":"Answers before you even have to ask.","introduction":"Can''t find what you''re looking for? Reach out and our team will help directly.","groups":[{"id":"booking","heading":"Booking & appointments","items":[{"id":"book","question":"How do I book a test?","answer":"Use the Book an Appointment page to choose a date, time and location, or call/WhatsApp our front desk and we''ll confirm your booking personally."},{"id":"walkin","question":"Can I book for a walk-in visit instead of scheduling ahead?","answer":"Yes. Walk-ins are welcome during opening hours, though booking ahead helps us prepare for your specific test."},{"id":"request","question":"Do I need a doctor''s request form?","answer":"Some tests require a referring doctor''s request; others can be booked directly. If you''re unsure, share the test name with our front desk and they''ll confirm."}]},{"id":"prep","heading":"Preparing for your test","items":[{"id":"fast","question":"Do I need to fast before my test?","answer":"Some tests, such as fasting blood sugar or a lipid profile, require 8–12 hours of fasting. Your booking confirmation will tell you if fasting applies to your test."},{"id":"bring","question":"What should I bring on the day?","answer":"Bring a valid ID, your doctor''s request form if you have one, and your booking reference. If it''s a repeat test, previous results are helpful but not required."}]},{"id":"home","heading":"Home sample collection","items":[{"id":"how","question":"How does home sample collection work?","answer":"Book a home visit through our Home Collection page or by WhatsApp. A trained phlebotomist arrives at your chosen time with sterile, single-use equipment to collect your sample."},{"id":"coverage","question":"Is home collection available everywhere?","answer":"Coverage depends on your location. Let us know your address when booking and we''ll confirm whether home collection is available for you."}]},{"id":"results","heading":"Accessing your results","items":[{"id":"ready","question":"How will I know when my result is ready?","answer":"We notify you by SMS, email or WhatsApp once your report has been reviewed and released, along with your lab reference number and a one-time access code."},{"id":"view","question":"How do I view my result online?","answer":"Visit the Access Your Results page and enter your lab reference number and one-time access code to securely view or download your report."},{"id":"help","question":"Can I get help understanding my result?","answer":"Yes. Contact our records desk and a member of our team will arrange a call to walk you through your report. We recommend discussing results with your physician for clinical decisions."}]}],"ctaHeading":"Still have a question?","ctaDescription":"Our team replies quickly on WhatsApp or by phone."}'::jsonb
where page_key='faq' and draft_content='{}'::jsonb;

update public.website_pages
set draft_content = '{"pageTitle":"Screening packages built around real lives, not long lists.","introduction":"Each package bundles the tests that matter, with a clear written summary you can take to your doctor.","pricingNote":"Pricing confirmed when you enquire or book.","packages":[{"id":"basic","name":"Basic Health Screening","description":"A dependable annual baseline for healthy adults.","featured":false,"tests":["Full blood count","Blood sugar (FBS)","Urinalysis","Blood pressure & BMI review"]},{"id":"executive","name":"Executive Health Screening","description":"Our most complete profile for leaders and frequent travellers.","featured":true,"tests":["Full blood count & ESR","Liver, kidney and lipid panels","HbA1c & thyroid profile","PSA / cervical screening"]},{"id":"women","name":"Women''s Health","description":"Hormonal, reproductive and wellness markers for women.","featured":false,"tests":["Hormonal profile","Pap smear / cytology","Iron studies","Thyroid function"]},{"id":"men","name":"Men''s Health","description":"Cardiometabolic and prostate-focused screening for men.","featured":false,"tests":["PSA","Lipid profile","Testosterone","Liver & kidney function"]},{"id":"corporate","name":"Corporate Screening","description":"On-site collection and consolidated reporting for teams.","featured":false,"tests":["Pre-employment panel","On-site sample collection","Group HR reporting","Annual review"]},{"id":"preventive","name":"Preventive Health Package","description":"Early-detection markers for families with risk history.","featured":false,"tests":["Cancer marker screen","Diabetes risk panel","Cardiac markers","Vitamin D & B12"]}]}'::jsonb
where page_key='packages' and draft_content='{}'::jsonb;

update public.website_pages
set draft_content = '{"pageTitle":"Booking a test should take two minutes, not two calls.","introduction":"Pick your test, choose a time, and tell us where to meet you. Our front desk confirms every booking personally.","bookingNotice":"Select a test, preferred date and time, then choose whether you will visit the laboratory or request home collection.","confirmationTitle":"Booking received","confirmationMessage":"Your request has been submitted successfully. Our front desk will contact you to confirm the appointment."}'::jsonb
where page_key='booking' and draft_content='{}'::jsonb;

update public.website_pages
set draft_content = '{"pageTitle":"Your results. Yours alone.","introduction":"No public patient portal, no shared inbox. Enter your lab reference number and the one-time access code sent to you to view your report.","accessInstructions":"Both fields are printed on your sample receipt and sent by SMS or email when your result is released.","helpMessage":"Didn''t receive a code? Email the laboratory records desk or visit the laboratory with a valid ID."}'::jsonb
where page_key='results' and draft_content='{}'::jsonb;
